---
--- Generated by Luanalysis
--- Created by philip_nori.
--- DateTime: 10.11.20 17:38
---
while number == nil do
    io.write("Gebe eine Zahl ein: ")
    io.flush()
    number = io.read("*l")
    print(number)
    io.flush()
    number = tonumber(number)
end
number = polynom1(number)
print("Das Ergebnis ist: ", number)



-- Zahl überprüfer
function isnumber(y)
    if type(y) == "number" then
        return 1
    else
        return -1
    end
end