---
--- Generated by Luanalysis
--- Created by philip_nori.
--- DateTime: 09.11.20 18:57
---

local answer
local a, b, c

---main programm
repeat
    print("Hallo User")
    io.write("Gebe eines dieser zeichen ein:")
    io.write("+ = plusrechnen\n")
    io.write("- = minusrechnen\n")
    io.write("* = malrechnen\n")
    io.write("/ = geteiltrechnen\n")
    io.write("e = exit\n")

    io.flush()
    answer = io.read()

    if answer == "+" then
        io.write(answer)

    elseif answer == "-" then

        io.write(answer)
    end

until answer == "exit"
